POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
  "name": "Billy Testerman",
  "number": "T35T"
}

###

DELETE http://localhost:3001/api/persons/6220d2aaa2c57cde41e1c68e

###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/1