POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
  "name": "Billy Testerman",
  "number": "T35T"
}

###

POST http://localhost:3001/api/persons HTTP/1.1

###
DELETE http://localhost:3001/api/persons/6220eb4787a08870aea4a4e0

###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/1

###

PUT http://localhost:3001/api/persons/6220ff2d07b6992b8b338010
content-type: application/json

{
  "name": "Billy Testerman",
  "number": "123-456-789"
}